CREATE DATABASE IF NOT EXISTS clinic_system;
USE clinic_system;

CREATE TABLE IF NOT EXISTS clinic_state (
  state_key VARCHAR(32) PRIMARY KEY,
  state JSON NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
